/* CONTROLE DE HIDRATAÇÃO — V2 com data local e reset visual à meia-noite */
(() => {
  "use strict";
  const STORAGE_KEY="planoAlimentar_hidratacao_v1", DEFAULT_GOAL=2500, PORTIONS=[200,250,300,500,750];
  const key=(d=new Date())=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`};
  const load=()=>{try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");return{goal:Number(x.goal)>0?Number(x.goal):DEFAULT_GOAL,days:x.days&&typeof x.days==="object"?x.days:{},settings:x.settings||{}}}catch{return{goal:DEFAULT_GOAL,days:{},settings:{}}}};
  let state=load();
  const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
  const day=()=>state.days[key()]||(state.days[key()]={total:0,entries:[]});
  const ml=v=>Number(v).toLocaleString("pt-BR")+" ml";
  const liters=v=>(Number(v)/1000).toLocaleString("pt-BR",{minimumFractionDigits:1,maximumFractionDigits:2})+" L";
  const pct=(t,g)=>g?Math.min(100,Math.round(t/g*100)):0;
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
  const time=v=>new Date(v).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});
  function styles(){if(document.getElementById("agua-final-styles"))return;const s=document.createElement("style");s.id="agua-final-styles";s.textContent=`#agua-app{max-width:1260px;margin:22px auto;padding:0 20px;color:#17352d;font-family:Arial}#agua-app *{box-sizing:border-box}.agua-card{background:#fffdf8;border:1px solid #d8d5c7;border-radius:22px;overflow:hidden;box-shadow:0 8px 24px rgba(23,53,45,.08)}.agua-header{padding:20px 24px;background:linear-gradient(135deg,#176b52,#2d8a6a);color:#fff;display:flex;justify-content:space-between;align-items:center;gap:18px}.agua-header h2{margin:0 0 4px}.agua-header p{margin:0;opacity:.9;font-size:14px}.agua-percent{min-width:78px;text-align:center;padding:10px;border-radius:14px;background:#ffffff25;font-weight:800}.agua-percent strong{display:block;font-size:23px}.agua-body{padding:20px 24px}.agua-values{display:flex;gap:8px;align-items:baseline}.agua-values strong{font-size:30px;color:#176b52}.agua-progress{height:16px;margin-top:10px;background:#e7e4d8;border-radius:99px;overflow:hidden}.agua-progress-bar{height:100%;background:#176b52}.agua-goal{margin-top:6px;color:#60746c;font-size:13px}.agua-actions{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:18px}.agua-btn,.agua-secondary,.agua-danger{border:0;border-radius:10px;padding:10px;font-weight:800;cursor:pointer}.agua-btn{background:#176b52;color:#fff}.agua-secondary{background:#e8efe5;color:#176b52}.agua-danger{background:#f5e5e1;color:#8b3e31}.agua-lower{display:grid;grid-template-columns:1.3fr .7fr;gap:14px;margin-top:16px}.agua-panel{border:1px solid #e1dfd3;border-radius:15px;padding:14px;background:#fff}.agua-entry{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #eeeade}.agua-entry button{border:0;background:transparent;color:#9a4b3c;font-weight:800}.agua-history-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.agua-day{padding:9px 4px;text-align:center;border-radius:10px;background:#f0eee5}.agua-day.today{outline:2px solid #176b52}.agua-day small,.agua-day strong{display:block}.agua-day strong{color:#176b52;margin-top:4px;font-size:12px}.agua-note{margin-top:12px;color:#6a7771;font-size:12px}@media(max-width:800px){#agua-app{padding:0 12px}.agua-actions{grid-template-columns:repeat(2,1fr)}.agua-lower{grid-template-columns:1fr}.agua-history-grid{grid-template-columns:repeat(4,1fr)}}`;document.head.appendChild(s)}
  function render(){const app=document.getElementById("agua-app");if(!app)return;const d=day(),goal=state.goal,total=Number(d.total)||0,p= pct(total,goal),last=[];for(let i=6;i>=0;i--){const x=new Date();x.setHours(12,0,0,0);x.setDate(x.getDate()-i);const k=key(x);last.push({key:k,date:x,total:Number(state.days[k]?.total||0)})}const entries=[...(d.entries||[])].reverse();app.innerHTML=`<section class="agua-card"><header class="agua-header"><div><h2>💧 Hidratação diária</h2><p>Acompanhe sua ingestão de água ao longo do dia.</p></div><div class="agua-percent"><strong>${p}%</strong><small>${total>=goal?"Meta atingida":"do objetivo"}</small></div></header><div class="agua-body"><div class="agua-values"><strong>${liters(total)}</strong><span>de ${liters(goal)}</span></div><div class="agua-progress"><div class="agua-progress-bar" style="width:${p}%"></div></div><div class="agua-goal">Meta diária: <b>${ml(goal)}</b></div><div class="agua-actions">${PORTIONS.map(v=>`<button class="agua-btn" data-add="${v}">+ ${v} ml</button>`).join("")}</div><div class="agua-lower"><div class="agua-panel"><h3>🕘 Registros de hoje</h3>${entries.length?entries.map((e,i)=>`<div class="agua-entry"><span>💧 <b>${ml(e.amount)}</b> — ${time(e.time)}</span><button data-remove="${d.entries.length-1-i}">Remover</button></div>`).join(""):"<div>Nenhum registro hoje.</div>"}</div><div class="agua-panel"><h3>⚙️ Meta</h3><label>Meta diária (ml)<input id="agua-goal-input" type="number" min="500" max="10000" step="100" value="${esc(goal)}"></label><div style="display:flex;gap:8px;margin-top:10px"><button class="agua-secondary" id="agua-save-goal">Salvar meta</button><button class="agua-danger" id="agua-reset-day">Zerar hoje</button></div></div></div><div class="agua-panel" style="margin-top:14px"><h3>📅 Últimos 7 dias</h3><div class="agua-history-grid">${last.map(x=>`<div class="agua-day ${x.key===key()?"today":""}"><small>${x.key===key()?"Hoje":x.date.toLocaleDateString("pt-BR",{weekday:"short"})}</small><strong>${liters(x.total)}</strong><span style="font-size:11px">${pct(x.total,goal)}%</span></div>`).join("")}</div></div><div class="agua-note">💡 A meta é configurável. Necessidades de hidratação variam conforme pessoa, clima, atividade física e orientação profissional.</div></div></section>`;
    app.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>{const n=Number(b.dataset.add),x=day();x.total+=n;x.entries.push({amount:n,time:new Date().toISOString()});save();render()});
    app.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.remove),x=day();if(x.entries[i]){x.total=Math.max(0,x.total-Number(x.entries[i].amount||0));x.entries.splice(i,1);save();render()}});
    app.querySelector("#agua-save-goal")?.addEventListener("click",()=>{state.goal=Math.min(10000,Math.max(500,Math.round(Number(app.querySelector("#agua-goal-input").value)||DEFAULT_GOAL)));save();render()});
    app.querySelector("#agua-reset-day")?.addEventListener("click",()=>{state.days[key()]={total:0,entries:[]};save();render()});
  }
  function mount(){if(document.getElementById("agua-app"))return;styles();const app=document.createElement("div");app.id="agua-app";(document.querySelector(".wrap")||document.body).prepend(app);render()}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount,{once:true});else mount();
  window.PlanoAlimentarAgua={adicionar:ml=>{const n=Number(ml);if(n>0){const d=day();d.total+=n;d.entries.push({amount:n,time:new Date().toISOString()});save();render()}},obterHoje:()=>JSON.parse(JSON.stringify(day())),obterMeta:()=>state.goal,redefinirHoje:()=>{state.days[key()]={total:0,entries:[]};save();render()}};
  window.addEventListener("planoAlimentar:novoDia",()=>{state=load();render()});
  window.addEventListener("storage",()=>{state=load();render()});
})();