(() => {
"use strict";
const ID="calendarioPlanoAlimentar", W="planoAlimentar_hidratacao_v1", A="planoAlimentar_atividade_v1", C="planoAlimentar_checklist_v2", P="planoAlimentar_peso_v1";
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}};
const pad=n=>String(n).padStart(2,"0"), key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
let cursor=new Date(); cursor.setDate(1);
function data(k){const w=read(W,{goal:2500,days:{}}),wd=w.days?.[k]||{},a=read(A,{goal:30,records:[]}),ar=(a.records||[]).filter(x=>x.date===k),p=read(P,[]),pr=(p||[]).find(x=>x.data===k||x.date===k),c=read(C,{data:"",itens:{}});return{water:+(wd.total||0),wg:+(w.goal||2500),act:ar.reduce((s,x)=>s+(+x.minutes||0),0),ag:+(a.goal||30),weight:pr?.peso,check:c.data===k?Object.values(c.itens||{}).filter(Boolean).length:0,checkTotal:c.data===k?Object.keys(c.itens||{}).length:0}}
function css(){if(document.getElementById("cal-style"))return;const s=document.createElement("style");s.id="cal-style";s.textContent=`#${ID}{max-width:1200px;margin:18px auto;padding:0 20px;font-family:Arial;color:#17352d}.cal-card{background:#fffdf8;border:1px solid #d8d5c7;border-radius:20px;overflow:hidden;box-shadow:0 6px 20px #17352d14}.cal-head{padding:18px 20px;background:linear-gradient(135deg,#176b52,#2d8a6a);color:white;display:flex;justify-content:space-between;gap:12px;align-items:center}.cal-head h2{margin:0}.cal-head p{margin:5px 0;font-size:13px}.cal-actions{display:flex;gap:6px;flex-wrap:wrap}.cal-actions button,.cal-month button{border:0;border-radius:9px;padding:9px 11px;font-weight:800;cursor:pointer}.cal-actions button{background:#ffffff22;color:white}.cal-body{padding:16px}.cal-month{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.cal-grid,.cal-week{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.cal-week div{text-align:center;font-size:11px;font-weight:800;padding:5px;color:#687871}.cal-day{min-height:72px;border:1px solid #dedacf;border-radius:10px;background:white;padding:7px;text-align:left;cursor:pointer}.cal-day.today{border:2px solid #176b52}.cal-day.muted{opacity:.4}.cal-day b{display:block}.marks{margin-top:7px;font-size:13px}.detail{margin-top:15px;border:1px solid #dedacf;border-radius:12px;padding:13px;background:white}.detail-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.detail-item{background:#f3f3eb;padding:10px;border-radius:9px}.detail-item b{display:block;color:#176b52}@media(max-width:700px){#${ID}{padding:0 10px}.cal-head{flex-direction:column;align-items:flex-start}.cal-day{min-height:55px}.detail-grid{grid-template-columns:repeat(2,1fr)}}`;
document.head.appendChild(s)}
function render(){let box=document.getElementById(ID);if(!box){box=document.createElement("section");box.id=ID;const p=document.getElementById("painelGeralFinal");(p?.parentNode||document.querySelector(".wrap")||document.body).appendChild(box)}const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),off=first.getDay(),days=new Date(y,m+1,0).getDate(),total=Math.ceil((off+days)/7)*7;let cells="";for(let i=0;i<total;i++){const n=i-off+1,d=new Date(y,m,n),k=key(d),x=data(k),muted=n<1||n>days,marks=(x.water?"💧":"")+(x.act?" 🏃":"")+(x.weight?" ⚖️":"")+(x.checkTotal&&x.check===x.checkTotal?" ☑️":"");cells+=`<button class="cal-day ${muted?"muted":""} ${k===key(new Date())?"today":""}" data-k="${k}"><b>${d.getDate()}</b><div class="marks">${marks}</div></button>`}box.innerHTML=`<div class="cal-card"><div class="cal-head"><div><h2>📅 Calendário e histórico</h2><p>Consulte seus registros por dia.</p></div><div class="cal-actions"><button id="cal-today">Hoje</button><button id="cal-prev">‹ Anterior</button><button id="cal-next">Próximo ›</button></div></div><div class="cal-body"><div class="cal-month"><button id="cal-p">‹</button><strong>${cursor.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</strong><button id="cal-n">›</button></div><div class="cal-week"><div>Dom</div><div>Seg</div><div>Ter</div><div>Qua</div><div>Qui</div><div>Sex</div><div>Sáb</div></div><div class="cal-grid">${cells}</div><div class="detail" id="cal-detail">Clique em um dia para ver o resumo.</div></div></div>`;
const nav=(d)=>{cursor.setMonth(cursor.getMonth()+d);render()};["cal-prev","cal-p"].forEach(id=>document.getElementById(id).onclick=()=>nav(-1));["cal-next","cal-n"].forEach(id=>document.getElementById(id).onclick=()=>nav(1));document.getElementById("cal-today").onclick=()=>{cursor=new Date();cursor.setDate(1);render()};box.querySelectorAll("[data-k]").forEach(b=>b.onclick=()=>{const x=data(b.dataset.k);document.getElementById("cal-detail").innerHTML=`<strong>📆 ${new Date(b.dataset.k+"T12:00:00").toLocaleDateString("pt-BR")}</strong><div class="detail-grid"><div class="detail-item"><b>💧 ${(x.water/1000).toLocaleString("pt-BR",{maximumFractionDigits:2})} L</b><small>meta ${(x.wg/1000).toLocaleString("pt-BR",{maximumFractionDigits:2})} L</small></div><div class="detail-item"><b>🏃 ${x.act} min</b><small>meta ${x.ag} min</small></div><div class="detail-item"><b>☑️ ${x.check}/${x.checkTotal}</b><small>checklist</small></div><div class="detail-item"><b>⚖️ ${x.weight?x.weight+" kg":"—"}</b><small>peso</small></div></div>`})}
function start(){css();render()}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start);else start();
})();