/* EDITOR DO PLANO ALIMENTAR — V3 FINAL
   Plano original totalmente editável + novas receitas + substituições.
   Correção: migra uma vez as substituições originais para edições antigas sem sobrescrever exclusões futuras.
*/
(()=>{
'use strict';
const KEY='planoAlimentar_editorPlano_v4',OLD='planoAlimentar_editorPlano_v3',OLD2='planoAlimentar_editorPlano_v2',ID='editorPlanoV2';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const parseSubs=f=>{try{const b=$('.swap',f),v=b?.dataset?.subs?JSON.parse(b.dataset.subs):[];return Array.isArray(v)?v.map(String).filter(Boolean):[]}catch{return[]}};
const norm=f=>({icon:String(f?.icon||'🍽️'),name:String(f?.name||''),qty:String(f?.qty||''),subs:Array.isArray(f?.subs)?f.subs.map(String).filter(Boolean):[]});
function original(id){const e=document.getElementById(id);if(!e)return null;return{id,title:$('h2',e)?.textContent.trim()||id,time:$('.time',e)?.textContent.trim()||'',icon:'🍽️',notes:$(' .notes',e)?.innerHTML||'',foods:$$('.food',e).map(f=>norm({icon:$('.food-icon',f)?.textContent.trim(),name:$('.food-name',f)?.textContent.trim(),qty:$('.food-qty',f)?.textContent.trim(),subs:parseSubs(f)}))}}
function migrate(x){if(!x||typeof x!=='object')return null;x.meals||={};x.customMeals||=[];x.disabledOriginal||=[];if(x.__subsMigrationV4)return x;Object.keys(x.meals).forEach(id=>{const o=original(id),m=x.meals[id];if(!o||!m)return;m.foods=(m.foods||o.foods||[]).map((f,i)=>{const base=norm(f),of=o.foods?.find(z=>z.name===base.name)||o.foods?.[i];if(!Array.isArray(f.subs)||f.subs.length===0)base.subs=of?.subs||[];return base});});x.__subsMigrationV4=true;return x}
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));if(x&&typeof x==='object')return x;x=JSON.parse(localStorage.getItem(OLD));if(x&&typeof x==='object'){x=migrate(x);localStorage.setItem(KEY,JSON.stringify(x));return x}x=JSON.parse(localStorage.getItem(OLD2));if(x&&typeof x==='object'){x=migrate(x);localStorage.setItem(KEY,JSON.stringify(x));return x}}catch{}return{meals:{},customMeals:[],disabledOriginal:[],__subsMigrationV4:true}}
function state(){const x=load();x.meals||={};x.customMeals||=[];x.disabledOriginal||=[];return x}
const save=x=>localStorage.setItem(KEY,JSON.stringify({...x,__subsMigrationV4:true}));
const ids=()=>$$('.meal[id]').map(e=>e.id);
function current(id){const o=original(id),x=state();if(!x.meals[id])return o;const m={...o,...x.meals[id]};m.foods=(x.meals[id].foods||o?.foods||[]).map((f,i)=>norm({...f,subs:Array.isArray(f.subs)?f.subs:(o?.foods?.[i]?.subs||[])}));return m}
function css(){if($('#editor-plano-style'))return;const s=document.createElement('style');s.id='editor-plano-style';s.textContent=`#${ID}{max-width:1200px;margin:18px auto;padding:0 20px;font-family:Arial;color:#17352d}#${ID} *{box-sizing:border-box}.ep-card{background:#fffdf8;border:1px solid #d8d5c7;border-radius:20px;overflow:hidden;box-shadow:0 6px 20px #17352d14}.ep-head{padding:18px 20px;background:#f1f0e7}.ep-head h2{margin:0}.ep-head p{margin:6px 0;color:#60746c;font-size:13px}.ep-body{padding:16px 20px}.ep-info{padding:11px 14px;background:#eaf4ed;border:1px solid #c9decf;border-radius:12px;margin-bottom:14px;color:#176b52;font-size:12px}.ep-actions{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.ep-btn{border:0;border-radius:10px;padding:10px 13px;font-weight:800;cursor:pointer}.ep-primary{background:#176b52;color:#fff}.ep-soft{background:#e7eee5;color:#176b52}.ep-danger{background:#f5dfda;color:#8b3e31}.ep-list{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.ep-meal{border:1px solid #dedacf;border-radius:13px;padding:12px;background:#fff}.ep-meal strong{display:block}.ep-meal small{color:#687871}.ep-disabled{opacity:.55}.ep-badge{display:inline-block;margin-left:5px;padding:3px 7px;border-radius:20px;background:#e7eee5;color:#176b52;font-size:10px}.ep-editor{display:none;margin-top:14px;border-top:1px solid #e3e0d6;padding-top:14px}.ep-editor.show{display:block}.ep-grid{display:grid;grid-template-columns:1fr 150px 100px;gap:9px}.ep-field{display:grid;gap:5px;font-size:11px;font-weight:800}.ep-field input,.ep-field textarea{padding:9px;border:1px solid #d8d5c7;border-radius:9px;font:inherit}.ep-food{margin-top:10px;padding:10px;border:1px solid #e1ded4;border-radius:12px;background:#fff}.ep-food-main{display:grid;grid-template-columns:55px 1fr 180px 40px;gap:8px;align-items:center}.ep-food input{width:100%;padding:8px;border:1px solid #d8d5c7;border-radius:8px}.ep-x{border:0;border-radius:8px;background:#f5dfda;color:#8b3e31;padding:8px;cursor:pointer;font-weight:800}.ep-subs{margin:9px 0 0 63px;padding:9px;background:#f6f4ec;border-radius:10px}.ep-sub-row{display:grid;grid-template-columns:1fr 36px;gap:6px;margin-top:5px}.ep-sub-row input{padding:7px;border:1px solid #d8d5c7;border-radius:8px}.ep-sub-add{margin-top:7px}.ep-hint{margin:10px 0;color:#6d7c75;font-size:12px;line-height:1.4}.ep-note{margin-top:10px}.ep-note textarea{width:100%;min-height:75px}.ep-empty{padding:10px;color:#71817a;font-size:12px}@media(max-width:700px){#${ID}{padding:0 10px}.ep-list,.ep-grid{grid-template-columns:1fr}.ep-food-main{grid-template-columns:45px 1fr 35px}.ep-food-main .ep-qty{grid-column:2}.ep-food-main .ep-x{grid-column:3;grid-row:1 / span 2}.ep-subs{margin-left:0}}`;document.head.appendChild(s)}
function food(f){const subs=(f.subs||[]).map(v=>`<div class="ep-sub-row"><input class="ep-sub" value="${esc(v)}"><button class="ep-x ep-sub-remove" type="button">×</button></div>`).join('');return `<div class="ep-food" data-food><div class="ep-food-main"><input class="ep-icon" value="${esc(f.icon)}" maxlength="4"><input class="ep-name" value="${esc(f.name)}" placeholder="Nome do alimento"><input class="ep-qty" value="${esc(f.qty)}" placeholder="Quantidade / medida"><button class="ep-x ep-food-remove" type="button">×</button></div><div class="ep-subs"><b>🔄 Opções de substituição</b><div class="ep-sub-list">${subs||'<div class="ep-empty">Nenhuma substituição cadastrada.</div>'}</div><button class="ep-btn ep-soft ep-sub-add" type="button">＋ Nova substituição</button></div></div>`}
function render(){let box=$('#'+ID);if(!box){box=document.createElement('section');box.id=ID;const w=$('.wrap')||document.body;w.appendChild(box)}const x=state(),list=ids().map(id=>{const d=current(id);return{id,title:d?.title||id,time:d?.time||'',disabled:x.disabledOriginal.includes(id)}});box.innerHTML=`<div class="ep-card"><div class="ep-head"><h2>🍽️ Plano alimentar e receitas</h2><p>Edite o plano original, horários, alimentos, quantidades, ícones e todas as opções de substituição. Crie novas receitas e alimentos.</p></div><div class="ep-body"><div class="ep-info">✅ O plano original é totalmente editável. As substituições existentes são preservadas ao salvar.</div><div class="ep-actions"><button class="ep-btn ep-primary" id="ep-new">＋ Nova receita/refeição</button><button class="ep-btn ep-soft" id="ep-reset-all">↺ Restaurar prescrição original</button></div><div class="ep-list">${list.map(m=>`<div class="ep-meal ${m.disabled?'ep-disabled':''}"><strong>${esc(m.title)}${m.disabled?'<span class="ep-badge">DESATIVADA</span>':''}</strong><small>${esc(m.time)}</small><div style="margin-top:8px"><button class="ep-btn ep-soft" data-edit="${esc(m.id)}">✏️ Editar</button>${m.disabled?`<button class="ep-btn ep-soft" data-enable="${esc(m.id)}">Reativar</button>`:`<button class="ep-btn ep-danger" data-disable="${esc(m.id)}">Desativar</button>`}<button class="ep-btn ep-soft" data-reset="${esc(m.id)}">Restaurar</button></div></div>`).join('')}${x.customMeals.map((m,i)=>`<div class="ep-meal"><strong>${esc(m.title)}<span class="ep-badge">NOVA</span></strong><small>${esc(m.time)} • personalizada</small><div style="margin-top:8px"><button class="ep-btn ep-soft" data-ce="${i}">✏️ Editar</button><button class="ep-btn ep-danger" data-cd="${i}">Excluir</button></div></div>`).join('')}</div><div class="ep-editor" id="ep-editor"></div></div></div>`;bindList(box)}
function bindList(box){$$('[data-edit]',box).forEach(b=>b.onclick=()=>open(b.dataset.edit,false));$$('[data-ce]',box).forEach(b=>b.onclick=()=>open(Number(b.dataset.ce),true));$$('[data-reset]',box).forEach(b=>b.onclick=()=>{const x=state();delete x.meals[b.dataset.reset];x.disabledOriginal=x.disabledOriginal.filter(i=>i!==b.dataset.reset);save(x);apply();render()});$$('[data-disable]',box).forEach(b=>b.onclick=()=>{const x=state();if(!x.disabledOriginal.includes(b.dataset.disable))x.disabledOriginal.push(b.dataset.disable);save(x);apply();render()});$$('[data-enable]',box).forEach(b=>b.onclick=()=>{const x=state();x.disabledOriginal=x.disabledOriginal.filter(i=>i!==b.dataset.enable);save(x);apply();render()});$$('[data-cd]',box).forEach(b=>b.onclick=()=>{const x=state();x.customMeals.splice(Number(b.dataset.cd),1);save(x);apply();render()});$('#ep-new',box).onclick=()=>open(null,true);$('#ep-reset-all',box).onclick=()=>{save({meals:{},customMeals:[],disabledOriginal:[]});apply();render()}}
function open(id,custom){const x=state(),d=custom?(id===null?{title:'Nova receita',time:'',icon:'🍽️',notes:'',foods:[]}:x.customMeals[id]):current(id);if(!d)return;const e=$('#ep-editor');e.classList.add('show');e.dataset.custom=custom?'1':'0';e.dataset.id=id===null?'':String(id);e.innerHTML=`<div class="ep-grid"><label class="ep-field">Nome da receita<input id="ep-title" value="${esc(d.title)}"></label><label class="ep-field">Horário<input id="ep-time" type="time" value="${esc(String(d.time).match(/\d\d:\d\d/)?.[0]||'')}"></label><label class="ep-field">Ícone<input id="ep-icon" value="${esc(d.icon||'🍽️')}" maxlength="4"></label></div><div class="ep-hint">Edite livremente o plano original ou crie uma nova receita. As substituições podem ser adicionadas, alteradas ou removidas.</div><div id="ep-foods">${(d.foods||[]).map(food).join('')}</div><div class="ep-note"><label class="ep-field">Observações<textarea id="ep-notes">${esc(d.notes||'')}</textarea></label></div><div class="ep-actions"><button class="ep-btn ep-soft" id="ep-add">＋ Novo alimento</button><button class="ep-btn ep-primary" id="ep-save">💾 Salvar alterações</button><button class="ep-btn ep-danger" id="ep-cancel">Cancelar</button></div>`;$('#ep-add',e).onclick=()=>{const list=$('#ep-foods',e);list.insertAdjacentHTML('beforeend',food({icon:'🍽️',name:'',qty:'',subs:[]}));bindFoodRows(e)};$('#ep-save',e).onclick=()=>saveEditor(e,custom);$('#ep-cancel',e).onclick=()=>e.classList.remove('show');bindFoodRows(e);e.scrollIntoView({behavior:'smooth',block:'start'})}
function bindFoodRows(e){$$('[data-food]',e).forEach(r=>{$('.ep-food-remove',r).onclick=()=>r.remove();$('.ep-sub-add',r).onclick=()=>{$('.ep-sub-list',r).insertAdjacentHTML('beforeend','<div class="ep-sub-row"><input class="ep-sub" value=""><button class="ep-x ep-sub-remove" type="button">×</button></div>');bindFoodRows(e)};$$('.ep-sub-remove',r).forEach(b=>b.onclick=()=>b.closest('.ep-sub-row').remove())})}
function saveEditor(e,custom){const foods=$$('[data-food]',e).map(r=>norm({icon:$('.ep-icon',r).value,name:$('.ep-name',r).value,qty:$('.ep-qty',r).value,subs:$$('.ep-sub',r).map(v=>v.value).filter(Boolean)})).filter(f=>f.name);const d={title:$('#ep-title',e).value.trim()||'Refeição',time:$('#ep-time',e).value||'',icon:$('#ep-icon',e).value.trim()||'🍽️',notes:$('#ep-notes',e).value,foods};const x=state();if(custom){const i=e.dataset.id===''?null:Number(e.dataset.id);if(i===null)x.customMeals.push(d);else x.customMeals[i]=d}else{x.meals[e.dataset.id]=d;x.disabledOriginal=x.disabledOriginal.filter(i=>i!==e.dataset.id)}save(x);apply();render()}
function mealHTML(f){const subs=f.subs||[];return `<article class="food"><div class="food-icon">${esc(f.icon)}</div><div class="food-name">${esc(f.name)}</div><div class="food-qty">${esc(f.qty)}</div>${subs.length?`<button class="swap" data-subs="${esc(JSON.stringify(subs))}" type="button">Substituir ▾</button>`:'<span class="no-subs">Sem substituições</span>'}</article>`}
function apply(){const x=state();ids().forEach(id=>{const e=document.getElementById(id);if(!e)return;const d=x.meals[id];e.style.display=x.disabledOriginal.includes(id)?'none':'';if(!d)return;const h=$('h2',e);if(h)h.textContent=d.title;const t=$('.time',e);if(t)t.textContent=d.time||t.textContent;const f=$('.foods',e);if(f)f.innerHTML=(d.foods||[]).map(mealHTML).join('');const n=$('.notes',e);if(n&&d.notes!==undefined)n.innerHTML=d.notes});const c=$('#content');if(c){$$('.ep-custom-render').forEach(e=>e.remove());x.customMeals.forEach(d=>{const sec=document.createElement('section');sec.className='meal ep-custom-render';sec.innerHTML=`<div class="meal-head"><div class="time">${esc(d.time||'—')}</div><h2>${esc(d.title)}</h2></div><div class="foods">${(d.foods||[]).map(mealHTML).join('')}</div><div class="notes">${esc(d.notes||'')}</div>`;c.appendChild(sec)})}}
function init(){css();render();apply()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
