/* EDITOR DO PLANO ALIMENTAR — V2 */
(()=>{
'use strict';
const KEY='planoAlimentar_editorPlano_v2',ID='editorPlanoV2';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{meals:{},customMeals:[],disabledOriginal:[]}}catch{return{meals:{},customMeals:[],disabledOriginal:[]}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const state=()=>{const s=load();s.meals||={};s.customMeals||=[];s.disabledOriginal||=[];return s};
const ids=()=>$$('.meal[id]').map(x=>x.id);
const original=id=>{const e=document.getElementById(id);if(!e)return null;return{id,title:$('h2',e)?.textContent.trim()||id,time:$('.time',e)?.textContent.trim()||'',foods:$$('.food',e).map(f=>({icon:$('.food-icon',f)?.textContent.trim()||'🍽️',name:$('.food-name',f)?.textContent.trim()||'',qty:$('.food-qty',f)?.textContent.trim()||''}))}};
const current=id=>state().meals[id]||original(id);
function css(){if($('#editor-plano-style'))return;const s=document.createElement('style');s.id='editor-plano-style';s.textContent=`#${ID}{max-width:1200px;margin:18px auto;padding:0 20px;font-family:Arial;color:#17352d}#${ID} *{box-sizing:border-box}.ep-card{background:#fffdf8;border:1px solid #d8d5c7;border-radius:20px;overflow:hidden}.ep-head{padding:18px 20px;background:#f1f0e7}.ep-head h2{margin:0}.ep-head p{margin:6px 0;color:#60746c;font-size:13px}.ep-body{padding:16px 20px}.ep-actions{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.ep-btn{border:0;border-radius:10px;padding:10px 13px;font-weight:800;cursor:pointer}.ep-primary{background:#176b52;color:#fff}.ep-soft{background:#e7eee5;color:#176b52}.ep-danger{background:#f5dfda;color:#8b3e31}.ep-list{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.ep-meal{border:1px solid #dedacf;border-radius:13px;padding:12px;background:#fff}.ep-meal strong{display:block}.ep-meal small{color:#687871}.ep-disabled{opacity:.55}.ep-badge{display:inline-block;margin-left:5px;padding:3px 7px;border-radius:20px;background:#e7eee5;color:#176b52;font-size:10px}.ep-editor{display:none;margin-top:14px;border-top:1px solid #e3e0d6;padding-top:14px}.ep-editor.show{display:block}.ep-grid{display:grid;grid-template-columns:1fr 150px 100px;gap:9px}.ep-field{display:grid;gap:5px;font-size:11px;font-weight:800}.ep-field input{padding:9px;border:1px solid #d8d5c7;border-radius:9px}.ep-food{display:grid;grid-template-columns:55px 1fr 180px 40px;gap:8px;align-items:center;margin-top:8px;padding:8px;border:1px solid #e1ded4;border-radius:10px}.ep-food input{width:100%;padding:8px;border:1px solid #d8d5c7;border-radius:8px}.ep-x{border:0;border-radius:8px;background:#f5dfda;color:#8b3e31;padding:8px;cursor:pointer;font-weight:800}.ep-hint{margin:10px 0;color:#6d7c75;font-size:12px}@media(max-width:700px){#${ID}{padding:0 10px}.ep-list,.ep-grid{grid-template-columns:1fr}.ep-food{grid-template-columns:45px 1fr 35px}.ep-food .ep-qty{grid-column:2}.ep-food .ep-x{grid-column:3;grid-row:1 / span 2}}`;document.head.appendChild(s)}
function render(){let box=$('#'+ID);if(!box){box=document.createElement('section');box.id=ID;const w=$('.wrap')||document.body;w.insertBefore(box,w.children[1]||null)}const s=state(),orig=ids().map(id=>({id,title:current(id)?.title||id,time:current(id)?.time||'',disabled:s.disabledOriginal.includes(id)}));box.innerHTML=`<div class="ep-card"><div class="ep-head"><h2>🍽️ Plano alimentar e receitas</h2><p>Edite a prescrição, crie novas receitas e cadastre alimentos que não existem no plano original.</p></div><div class="ep-body"><div class="ep-actions"><button class="ep-btn ep-primary" id="ep-new">＋ Nova receita/refeição</button><button class="ep-btn ep-soft" id="ep-reset-all">↺ Restaurar prescrição original</button></div><div class="ep-list">${orig.map(m=>`<div class="ep-meal ${m.disabled?'ep-disabled':''}"><strong>${esc(m.title)}${m.disabled?'<span class="ep-badge">DESATIVADA</span>':''}</strong><small>${esc(m.time)}</small><div style="margin-top:8px"><button class="ep-btn ep-soft" data-edit="${esc(m.id)}">✏️ Editar</button>${m.disabled?`<button class="ep-btn ep-soft" data-enable="${esc(m.id)}">Reativar</button>`:`<button class="ep-btn ep-danger" data-disable="${esc(m.id)}">Desativar</button>`}<button class="ep-btn ep-soft" data-reset="${esc(m.id)}">Restaurar</button></div></div>`).join('')}${s.customMeals.map((m,i)=>`<div class="ep-meal"><strong>${esc(m.title)}<span class="ep-badge">NOVA</span></strong><small>${esc(m.time)} • personalizada</small><div style="margin-top:8px"><button class="ep-btn ep-soft" data-ce="${i}">✏️ Editar</button><button class="ep-btn ep-danger" data-cd="${i}">Excluir</button></div></div>`).join('')}</div><div class="ep-editor" id="ep-editor"></div></div></div>`;
$$('[data-edit]',box).forEach(b=>b.onclick=()=>open(b.dataset.edit,false));
$$('[data-reset]',box).forEach(b=>b.onclick=()=>{const x=state();delete x.meals[b.dataset.reset];x.disabledOriginal=x.disabledOriginal.filter(i=>i!==b.dataset.reset);save(x);apply();render()});
$$('[data-disable]',box).forEach(b=>b.onclick=()=>{if(confirm('Desativar esta receita original? Ela sairá do plano atual, mas ficará guardada para restauração.')){const x=state();if(!x.disabledOriginal.includes(b.dataset.disable))x.disabledOriginal.push(b.dataset.disable);save(x);apply();render()}});
$$('[data-enable]',box).forEach(b=>b.onclick=()=>{const x=state();x.disabledOriginal=x.disabledOriginal.filter(i=>i!==b.dataset.enable);save(x);apply();render()});
$$('[data-ce]',box).forEach(b=>b.onclick=()=>open(Number(b.dataset.ce),true));
$$('[data-cd]',box).forEach(b=>b.onclick=()=>{if(confirm('Excluir esta receita personalizada?')){const x=state();x.customMeals.splice(Number(b.dataset.cd),1);save(x);apply();render()}});
$('#ep-new',box).onclick=()=>open(null,true);
$('#ep-reset-all',box).onclick=()=>{if(confirm('Restaurar a prescrição original e remover as receitas personalizadas?')){save({meals:{},customMeals:[],disabledOriginal:[]});apply();render()}};
}
function open(id,custom){const s=state(),d=custom?(id===null?{title:'Nova receita',time:'',icon:'🍽️',foods:[]}:s.customMeals[id]):current(id);if(!d)return;const e=$('#ep-editor');e.classList.add('show');e.dataset.custom=custom?'1':'0';e.dataset.id=id===null?'':String(id);e.innerHTML=`<div class="ep-grid"><label class="ep-field">Nome da receita<input id="ep-title" value="${esc(d.title)}"></label><label class="ep-field">Horário<input id="ep-time" type="time" value="${esc(String(d.time).match(/\d\d:\d\d/)?.[0]||'')}"></label><label class="ep-field">Ícone<input id="ep-icon" value="${esc(d.icon||'🍽️')}" maxlength="4"></label></div><div class="ep-hint">Você pode criar alimentos totalmente novos. Eles não precisam existir na receita original nem no aplicativo.</div><div id="ep-foods">${(d.foods||[]).map(food).join('')}</div><div class="ep-actions"><button class="ep-btn ep-soft" id="ep-add">＋ Novo alimento</button><button class="ep-btn ep-primary" id="ep-save">💾 Salvar receita</button><button class="ep-btn ep-danger" id="ep-cancel">Cancelar</button></div>`;$('#ep-add',e).onclick=()=>$('#ep-foods',e).insertAdjacentHTML('beforeend',food({icon:'🍽️',name:'',qty:''}));$('#ep-save',e).onclick=()=>saveEditor(e,custom);$('#ep-cancel',e).onclick=()=>e.classList.remove('show');e.scrollIntoView({behavior:'smooth',block:'start'})}
function food(f){return `<div class="ep-food" data-food><input class="ep-icon" value="${esc(f.icon||'🍽️')}" maxlength="4"><input class="ep-name" value="${esc(f.name||'')}" placeholder="Nome do alimento"><input class="ep-qty" value="${esc(f.qty||'')}" placeholder="Quantidade / medida"><button class="ep-x" type="button">×</button></div>`}
function saveEditor(e,custom){const foods=$$('[data-food]',e).map(r=>({icon:$('.ep-icon',r).value.trim()||'🍽️',name:$('.ep-name',r).value.trim(),qty:$('.ep-qty',r).value.trim()})).filter(f=>f.name);const d={title:$('#ep-title',e).value.trim()||'Refeição',time:$('#ep-time',e).value||'',icon:$('#ep-icon',e).value.trim()||'🍽️',foods};const s=state();if(custom){const i=e.dataset.id===''?null:Number(e.dataset.id);if(i===null)s.customMeals.push(d);else s.customMeals[i]=d}else{s.meals[e.dataset.id]=d;s.disabledOriginal=s.disabledOriginal.filter(i=>i!==e.dataset.id)}save(s);apply();render()}
function apply(){const s=state();ids().forEach(id=>{const e=document.getElementById(id);if(!e)return;e.style.display=s.disabledOriginal.includes(id)?'none':'';const d=s.meals[id];if(!d)return;const h=$('h2',e);if(h)h.textContent=d.title;const t=$('.time',e);if(t)t.textContent=d.time||t.textContent;const f=$('.foods',e);if(f)f.innerHTML=d.foods.map(x=>`<article class="food"><div class="food-icon">${esc(x.icon)}</div><div class="food-name">${esc(x.name)}</div><div class="food-qty">${esc(x.qty)}</div><span class="no-subs">Personalizado</span></article>`).join('')});$$('.ep-custom-render').forEach(x=>x.remove());const c=$('#content');if(c)s.customMeals.forEach((d,i)=>{const sec=document.createElement('section');sec.className='meal ep-custom-render';sec.innerHTML=`<div class="meal-head"><div class="time">${esc(d.time||'—')}</div><h2>${esc(d.title)}</h2></div><div class="foods">${d.foods.map(x=>`<article class="food"><div class="food-icon">${esc(x.icon)}</div><div class="food-name">${esc(x.name)}</div><div class="food-qty">${esc(x.qty)}</div><span class="no-subs">Receita personalizada</span></article>`).join('')}</div>`;c.appendChild(sec)})}
function boot(){try{css();apply();render()}catch(e){console.warn('Editor de plano:',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
