/* EDITOR DO PLANO ALIMENTAR — V3
   Plano original totalmente editável + novas receitas + substituições.
*/
(()=>{
'use strict';
const KEY='planoAlimentar_editorPlano_v3',ID='editorPlanoV2';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const parseSubs=el=>{try{const raw=el?.getAttribute('data-subs');const v=raw?JSON.parse(raw):[];return Array.isArray(v)?v.map(String).filter(Boolean):[]}catch{return[]}};
const normalizeFood=f=>({icon:String(f?.icon||'🍽️'),name:String(f?.name||''),qty:String(f?.qty||''),subs:Array.isArray(f?.subs)?f.subs.map(String).filter(Boolean):[]});
const load=()=>{try{const raw=JSON.parse(localStorage.getItem(KEY));return raw&&typeof raw==='object'?raw:{meals:{},customMeals:[],disabledOriginal:[]}}catch{return{meals:{},customMeals:[],disabledOriginal:[]}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const state=()=>{const s=load();s.meals||={};s.customMeals||=[];s.disabledOriginal||=[];Object.keys(s.meals).forEach(k=>{if(s.meals[k])s.meals[k].foods=(s.meals[k].foods||[]).map(normalizeFood)});s.customMeals=s.customMeals.map(m=>({...m,foods:(m.foods||[]).map(normalizeFood)}));return s};
const ids=()=>$$('.meal[id]').map(x=>x.id);
const original=id=>{const e=document.getElementById(id);if(!e)return null;return{id,title:$('h2',e)?.textContent.trim()||id,time:$('.time',e)?.textContent.trim()||'',icon:'🍽️',notes:$('.notes',e)?.innerHTML||'',foods:$$('.food',e).map(f=>normalizeFood({icon:$('.food-icon',f)?.textContent.trim(),name:$('.food-name',f)?.textContent.trim(),qty:$('.food-qty',f)?.textContent.trim(),subs:parseSubs($('.swap',f))}))}};
const current=id=>state().meals[id]||original(id);
function css(){if($('#editor-plano-style'))return;const s=document.createElement('style');s.id='editor-plano-style';s.textContent=`#${ID}{max-width:1200px;margin:18px auto;padding:0 20px;font-family:Arial;color:#17352d}#${ID} *{box-sizing:border-box}.ep-card{background:#fffdf8;border:1px solid #d8d5c7;border-radius:20px;overflow:hidden;box-shadow:0 6px 20px rgba(23,53,45,.08)}.ep-head{padding:18px 20px;background:#f1f0e7}.ep-head h2{margin:0}.ep-head p{margin:6px 0;color:#60746c;font-size:13px;line-height:1.45}.ep-info{padding:11px 14px;background:#eaf4ed;border:1px solid #c9decf;border-radius:12px;margin-bottom:14px;color:#176b52;font-size:12px}.ep-actions{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.ep-btn{border:0;border-radius:10px;padding:10px 13px;font-weight:800;cursor:pointer}.ep-primary{background:#176b52;color:#fff}.ep-soft{background:#e7eee5;color:#176b52}.ep-danger{background:#f5dfda;color:#8b3e31}.ep-list{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.ep-meal{border:1px solid #dedacf;border-radius:13px;padding:12px;background:#fff}.ep-meal strong{display:block}.ep-meal small{color:#687871}.ep-disabled{opacity:.55}.ep-badge{display:inline-block;margin-left:5px;padding:3px 7px;border-radius:20px;background:#e7eee5;color:#176b52;font-size:10px}.ep-editor{display:none;margin-top:14px;border-top:1px solid #e3e0d6;padding-top:14px}.ep-editor.show{display:block}.ep-grid{display:grid;grid-template-columns:1fr 150px 100px;gap:9px}.ep-field{display:grid;gap:5px;font-size:11px;font-weight:800}.ep-field input,.ep-field textarea{padding:9px;border:1px solid #d8d5c7;border-radius:9px;font:inherit}.ep-food{margin-top:10px;padding:10px;border:1px solid #e1ded4;border-radius:12px;background:#fff}.ep-food-main{display:grid;grid-template-columns:55px 1fr 180px 40px;gap:8px;align-items:center}.ep-food input{width:100%;padding:8px;border:1px solid #d8d5c7;border-radius:8px}.ep-x{border:0;border-radius:8px;background:#f5dfda;color:#8b3e31;padding:8px;cursor:pointer;font-weight:800}.ep-subs{margin:9px 0 0 63px;padding:9px;background:#f6f4ec;border-radius:10px}.ep-subs-title{font-size:11px;font-weight:800;margin-bottom:6px}.ep-sub-row{display:grid;grid-template-columns:1fr 36px;gap:6px;margin-top:5px}.ep-sub-row input{padding:7px}.ep-sub-add{margin-top:7px}.ep-hint{margin:10px 0;color:#6d7c75;font-size:12px;line-height:1.4}.ep-note{margin-top:10px}.ep-note textarea{width:100%;min-height:75px}.ep-empty{padding:15px;color:#71817a;font-size:12px}@media(max-width:700px){#${ID}{padding:0 10px}.ep-list,.ep-grid{grid-template-columns:1fr}.ep-food-main{grid-template-columns:45px 1fr 35px}.ep-food-main .ep-qty{grid-column:2}.ep-food-main .ep-x{grid-column:3;grid-row:1 / span 2}.ep-subs{margin-left:0}.ep-sub-row{grid-template-columns:1fr 36px}}`;document.head.appendChild(s)}
function food(f){const subs=(f.subs||[]).map(sub=>`<div class="ep-sub-row" data-sub-row><input class="ep-sub" value="${esc(sub)}" placeholder="Ex.: Tapioca — 2 colheres de sopa"><button class="ep-x ep-sub-remove" type="button">×</button></div>`).join('');return `<div class="ep-food" data-food><div class="ep-food-main"><input class="ep-icon" value="${esc(f.icon||'🍽️')}" maxlength="4"><input class="ep-name" value="${esc(f.name||'')}" placeholder="Nome do alimento"><input class="ep-qty" value="${esc(f.qty||'')}" placeholder="Quantidade / medida"><button class="ep-x ep-food-remove" type="button">×</button></div><div class="ep-subs"><div class="ep-subs-title">🔄 Opções de substituição</div><div class="ep-sub-list">${subs||'<div class="ep-empty">Nenhuma substituição cadastrada.</div>'}</div><button class="ep-btn ep-soft ep-sub-add" type="button">＋ Nova substituição</button></div></div>`}
function render(){let box=$('#'+ID);if(!box){box=document.createElement('section');box.id=ID;const w=$('.wrap')||document.body;w.insertBefore(box,w.children[1]||null)}const s=state(),orig=ids().map(id=>({id,title:current(id)?.title||id,time:current(id)?.time||'',disabled:s.disabledOriginal.includes(id)}));box.innerHTML=`<div class="ep-card"><div class="ep-head"><h2>🍽️ Plano alimentar e receitas</h2><p>Agora o plano original também pode ser editado. Você pode alterar horários, alimentos, quantidades, ícones e todas as opções de substituição.</p></div><div class="ep-body"><div class="ep-info">✅ <b>Plano original editável:</b> nenhuma refeição fica bloqueada. As alterações são salvas neste navegador e podem ser restauradas individualmente quando necessário.</div><div class="ep-actions"><button class="ep-btn ep-primary" id="ep-new">＋ Nova receita/refeição</button><button class="ep-btn ep-soft" id="ep-reset-all">↺ Restaurar prescrição original</button></div><div class="ep-list">${orig.map(m=>`<div class="ep-meal ${m.disabled?'ep-disabled':''}"><strong>${esc(m.title)}${m.disabled?'<span class="ep-badge">DESATIVADA</span>':''}</strong><small>${esc(m.time)}</small><div style="margin-top:8px"><button class="ep-btn ep-soft" data-edit="${esc(m.id)}">✏️ Editar</button>${m.disabled?`<button class="ep-btn ep-soft" data-enable="${esc(m.id)}">Reativar</button>`:`<button class="ep-btn ep-danger" data-disable="${esc(m.id)}">Desativar</button>`}<button class="ep-btn ep-soft" data-reset="${esc(m.id)}">Restaurar</button></div></div>`).join('')}${s.customMeals.map((m,i)=>`<div class="ep-meal"><strong>${esc(m.title)}<span class="ep-badge">NOVA</span></strong><small>${esc(m.time)} • personalizada</small><div style="margin-top:8px"><button class="ep-btn ep-soft" data-ce="${i}">✏️ Editar</button><button class="ep-btn ep-danger" data-cd="${i}">Excluir</button></div></div>`).join('')}</div><div class="ep-editor" id="ep-editor"></div></div></div>`;
$$('[data-edit]',box).forEach(b=>b.onclick=()=>open(b.dataset.edit,false));
$$('[data-reset]',box).forEach(b=>b.onclick=()=>{const x=state();delete x.meals[b.dataset.reset];x.disabledOriginal=x.disabledOriginal.filter(i=>i!==b.dataset.reset);save(x);apply();render()});
$$('[data-disable]',box).forEach(b=>b.onclick=()=>{if(confirm('Desativar esta refeição? Ela ficará guardada para restauração.')){const x=state();if(!x.disabledOriginal.includes(b.dataset.disable))x.disabledOriginal.push(b.dataset.disable);save(x);apply();render()}});
$$('[data-enable]',box).forEach(b=>b.onclick=()=>{const x=state();x.disabledOriginal=x.disabledOriginal.filter(i=>i!==b.dataset.enable);save(x);apply();render()});
$$('[data-ce]',box).forEach(b=>b.onclick=()=>open(Number(b.dataset.ce),true));
$$('[data-cd]',box).forEach(b=>b.onclick=()=>{if(confirm('Excluir esta receita personalizada?')){const x=state();x.customMeals.splice(Number(b.dataset.cd),1);save(x);apply();render()}});
$('#ep-new',box).onclick=()=>open(null,true);
$('#ep-reset-all',box).onclick=()=>{if(confirm('Restaurar o plano original e remover as receitas personalizadas?')){save({meals:{},customMeals:[],disabledOriginal:[]});apply();render()}};
}
function open(id,custom){const s=state(),d=custom?(id===null?{title:'Nova receita',time:'',icon:'🍽️',foods:[]}:s.customMeals[id]):current(id);if(!d)return;const e=$('#ep-editor');e.classList.add('show');e.dataset.custom=custom?'1':'0';e.dataset.id=id===null?'':String(id);e.innerHTML=`<div class="ep-grid"><label class="ep-field">Nome da receita<input id="ep-title" value="${esc(d.title)}"></label><label class="ep-field">Horário<input id="ep-time" type="time" value="${esc(String(d.time).match(/\d\d:\d\d/)?.[0]||'')}"></label><label class="ep-field">Ícone<input id="ep-icon" value="${esc(d.icon||'🍽️')}" maxlength="4"></label></div><div class="ep-hint">Você pode editar livremente o plano original ou criar uma nova receita. Em cada alimento, as substituições existentes são carregadas e podem ser alteradas, excluídas ou adicionadas.</div><div id="ep-foods">${(d.foods||[]).map(food).join('')}</div><div class="ep-note"><label class="ep-field">Observações da refeição<textarea id="ep-notes" placeholder="Observações, orientações ou restrições...">${esc(d.notes||'')}</textarea></label></div><div class="ep-actions" style="margin-top:12px"><button class="ep-btn ep-soft" id="ep-add">＋ Novo alimento</button><button class="ep-btn ep-primary" id="ep-save">💾 Salvar alterações</button><button class="ep-btn ep-danger" id="ep-cancel">Cancelar</button></div>`;bindEditor(e,custom);e.scrollIntoView({behavior:'smooth',block:'start'})}
function bindEditor(e,custom){$('#ep-add',e).onclick=()=>{$('#ep-foods',e).insertAdjacentHTML('beforeend',food({icon:'🍽️',name:'',qty:'',subs:[]}));bindFoodRows(e)};$('#ep-save',e).onclick=()=>saveEditor(e,custom);$('#ep-cancel',e).onclick=()=>e.classList.remove('show');bindFoodRows(e)}
function bindFoodRows(e){$$('[data-food]',e).forEach(row=>{const remove=$('.ep-food-remove',row);if(remove&&!remove.dataset.bound){remove.dataset.bound='1';remove.onclick=()=>row.remove()}const add=$('.ep-sub-add',row);if(add&&!add.dataset.bound){add.dataset.bound='1';add.onclick=()=>{$('.ep-sub-list',row).insertAdjacentHTML('beforeend','<div class="ep-sub-row" data-sub-row><input class="ep-sub" value="" placeholder="Ex.: Alimento substituto — quantidade"><button class="ep-x ep-sub-remove" type="button">×</button></div>');const last=$('.ep-sub-row:last-child',row);$('.ep-sub-remove',last).onclick=()=>last.remove();$('.ep-sub-list .ep-empty',row)?.remove()}}$$('.ep-sub-remove',row).forEach(btn=>{if(!btn.dataset.bound){btn.dataset.bound='1';btn.onclick=()=>btn.closest('[data-sub-row]')?.remove()}})})}
function saveEditor(e,custom){const foods=$$('[data-food]',e).map(r=>({icon:$('.ep-icon',r).value.trim()||'🍽️',name:$('.ep-name',r).value.trim(),qty:$('.ep-qty',r).value.trim(),subs:$$('.ep-sub',r).map(x=>x.value.trim()).filter(Boolean)})).filter(f=>f.name);const d={title:$('#ep-title',e).value.trim()||'Refeição',time:$('#ep-time',e).value||'',icon:$('#ep-icon',e).value.trim()||'🍽️',notes:$('#ep-notes',e).value.trim(),foods};const s=state();if(custom){const i=e.dataset.id===''?null:Number(e.dataset.id);if(i===null)s.customMeals.push(d);else s.customMeals[i]=d}else{s.meals[e.dataset.id]=d;s.disabledOriginal=s.disabledOriginal.filter(i=>i!==e.dataset.id)}save(s);apply();render()}
function mealFoodHTML(x){const subs=x.subs||[];return `<article class="food"><div class="food-icon">${esc(x.icon)}</div><div class="food-name">${esc(x.name)}</div><div class="food-qty">${esc(x.qty)}</div>${subs.length?`<button class="swap" data-subs="${esc(JSON.stringify(subs))}" type="button">Substituir ▾</button>`:'<span class="no-subs">Sem substituições</span>'}</article>`}
function apply(){const s=state();ids().forEach(id=>{const e=document.getElementById(id);if(!e)return;e.style.display=s.disabledOriginal.includes(id)?'none':'';const d=s.meals[id];if(!d)return;const h=$('h2',e);if(h)h.textContent=d.title;const t=$('.time',e);if(t)t.textContent=d.time||t.textContent;const f=$('.foods',e);if(f)f.innerHTML=d.foods.map(mealFoodHTML).join('');const n=$('.notes',e);if(n&&d.notes!==undefined)n.innerHTML=d.notes?d.notes:'<b>Observações</b><ul><li>Nenhuma observação registrada.</li></ul>';bindSwapButtons(e)});$$('.ep-custom-render').forEach(x=>x.remove());const c=$('#content');if(c)s.customMeals.forEach((d,i)=>{const sec=document.createElement('section');sec.className='meal ep-custom-render';sec.innerHTML=`<div class="meal-head"><div class="time">${esc(d.time||'—')}</div><h2>${esc(d.title)}</h2><button class="expand" type="button">Ver substituições</button></div><div class="foods">${d.foods.map(mealFoodHTML).join('')}</div>${d.notes?`<div class="notes">${esc(d.notes)}</div>`:''}`;c.appendChild(sec);bindSwapButtons(sec);$('.expand',sec).onclick=()=>sec.scrollIntoView({behavior:'smooth'})})}
function bindSwapButtons(root){$$('.swap',root).forEach(btn=>{if(btn.dataset.editorBound)return;btn.dataset.editorBound='1';btn.onclick=()=>{let subs=[];try{subs=JSON.parse(btn.getAttribute('data-subs')||'[]')}catch{};const old=document.querySelector('.ep-swap-popup');if(old)old.remove();const box=document.createElement('div');box.className='ep-swap-popup';box.style.cssText='position:fixed;inset:auto 20px 20px 20px;max-width:600px;margin:auto;background:#fffdf8;border:1px solid #d8d5c7;border-radius:16px;padding:16px;z-index:90;box-shadow:0 18px 50px #0004';box.innerHTML=`<strong>🔄 Opções de substituição</strong><button type="button" style="float:right;border:0;border-radius:50%;width:28px;height:28px" data-close>×</button><div style="margin-top:10px">${subs.map(x=>`<div style="padding:9px;border-bottom:1px solid #eee">${esc(x)}</div>`).join('')||'<div style="padding:9px;color:#777">Nenhuma substituição cadastrada.</div>'}</div>`;document.body.appendChild(box);$('[data-close]',box).onclick=()=>box.remove()})})}
function boot(){try{css();apply();render()}catch(e){console.warn('Editor de plano:',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
